In [1]:

import pandas as pd
import numpy as np

data = {
    "Customer_ID": [
        101, 102, 103, 104, 105, 106, 107, 108,
        109, 110, 111, 112, 113, 114, 115
    ],
    "Name": [
        " Rahul ", "Priya", "ARUN", " Meena",
        None, "Suresh ", "Anu", "rahul",
        "Priya ", None, "Kiran", " Meera",
        "John", "sneha", " Suresh"
    ],
    "Age": [
        25, 30, None, 28, 150, 35, -5, 29,
        None, 42, 19, 200, 31, None, 27
    ],
    "Gender": [
        "Male", "Female", "M", "female", None,
        "MALE", "F", "Male", "Female", "F",
        "male", None, "Male", "Female", "female"
    ],
    "City": [
        "Kochi", "kochi", "CHENNAI", "Chennai",
        None, "Mumbai", "mumbai", "Kochi",
        "Bangalore", "bangalore", None, "Delhi",
        "delhi", "Kochi", "KOCHI"
    ],
    "Purchase_Amount": [
        2500, 4500, 3200, None, 7500, 1200,
        -500, 3400, 5600, None, 1800, 9000,
        4500, 6200, None
    ],
    "Discount": [
        10, 5, None, 15, 20, None, 5, 10,
        0, 25, None, 15, 10, None, 5
    ],
    "Department": [
        "Electronics", "electronics", "Clothing",
        "CLOTHING", None, "Grocery", "grocery",
        "Electronics", "Clothing", "GROCERY",
        None, "Electronics", "electronics",
        "Grocery", "CLOTHING"
    ],
    "Joining_Date": [
        "2022-01-15", "2021-05-20", "2020-08-10",
        "2023-02-30", None, "2021-06-15",
        "2022-13-10", "2020-11-25", "2021-06-15",
        "2020-03-20", "2024-01-10", "2022-12-32",
        "2023-05-18", None, "2021-09-25"
    ],
    "Email": [
        "rahul@gmail.com", "priya@gmail.com",
        "arun@gmail.com", "meena@gmail", None,
        "suresh@gmail.com", "anu@gmail",
        "rahul@gmail.com", "priya@gmail.com",
        "kiran@gmail.com", None, "meera@gmail.com",
        "john@gmail.com", "sneha@gmail",
        "suresh@gmail.com"
    ]
}

df = pd.DataFrame(data)

df

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email
0,101,Rahul,25.0,Male,Kochi,2500.0,10.0,Electronics,2022-01-15,rahul@gmail.com
1,102,Priya,30.0,Female,kochi,4500.0,5.0,electronics,2021-05-20,priya@gmail.com
2,103,ARUN,NaN,M,CHENNAI,3200.0,NaN,Clothing,2020-08-10,arun@gmail.com
3,104,Meena,28.0,female,Chennai,NaN,15.0,CLOTHING,2023-02-30,meena@gmail
4,105,NaN,150.0,NaN,NaN,7500.0,20.0,NaN,NaN,NaN
5,106,Suresh,35.0,MALE,Mumbai,1200.0,NaN,Grocery,2021-06-15,suresh@gmail.com
6,107,Anu,-5.0,F,mumbai,-500.0,5.0,grocery,2022-13-10,anu@gmail
7,108,rahul,29.0,Male,Kochi,3400.0,10.0,Electronics,2020-11-25,rahul@gmail.com
8,109,Priya,NaN,Female,Bangalore,5600.0,0.0,Clothing,2021-06-15,priya@gmail.com
9,110,NaN,42.0,F,bangalore,NaN,25.0,GROCERY,2020-03-20,kiran@gmail.com
10,111,Kiran,19.0,male,NaN,1800.0,NaN,NaN,2024-01-10,NaN
11,112,Meera,200.0,NaN,Delhi,9000.0,15.0,Electronics,2022-12-32,meera@gmail.com
12,113,John,31.0,Male,delhi,4500.0,10.0,electronics,2023-05-18,john@gmail.com
13,114,sneha,NaN,Female,Kochi,6200.0,NaN,Grocery,NaN,sneha@gmail
14,115,Suresh,27.0,female,KOCHI,NaN,5.0,CLOTHING,2021-09-25,suresh@gmail.com

In [2]:

# Q1. Display the first 5 rows
df.head(5)

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email
0,101,Rahul,25.0,Male,Kochi,2500.0,10.0,Electronics,2022-01-15,rahul@gmail.com
1,102,Priya,30.0,Female,kochi,4500.0,5.0,electronics,2021-05-20,priya@gmail.com
2,103,ARUN,NaN,M,CHENNAI,3200.0,NaN,Clothing,2020-08-10,arun@gmail.com
3,104,Meena,28.0,female,Chennai,NaN,15.0,CLOTHING,2023-02-30,meena@gmail
4,105,NaN,150.0,NaN,NaN,7500.0,20.0,NaN,NaN,NaN

In [3]:

# Q2. Display the last 5 rows
df.tail(5)

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email
10,111,Kiran,19.0,male,NaN,1800.0,NaN,NaN,2024-01-10,NaN
11,112,Meera,200.0,NaN,Delhi,9000.0,15.0,Electronics,2022-12-32,meera@gmail.com
12,113,John,31.0,Male,delhi,4500.0,10.0,electronics,2023-05-18,john@gmail.com
13,114,sneha,NaN,Female,Kochi,6200.0,NaN,Grocery,NaN,sneha@gmail
14,115,Suresh,27.0,female,KOCHI,NaN,5.0,CLOTHING,2021-09-25,suresh@gmail.com

In [4]:

# Q3. Find the number of rows and columns
df.shape

(15, 10)

In [5]:

# Q4. Display all column names
df.columns

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Purchase_Amount',
       'Discount', 'Department', 'Joining_Date', 'Email'],
      dtype='str')

In [6]:

# Q5. Display the datatype of every column
df.dtypes

Customer_ID          int64
Name                   str
Age                float64
Gender                 str
City                   str
Purchase_Amount    float64
Discount           float64
Department             str
Joining_Date           str
Email                  str
dtype: object

In [7]:

# Q6. Statistical summary of numerical columns
df.describe()

       Customer_ID         Age  Purchase_Amount   Discount
count    15.000000   12.000000        12.000000  11.000000
mean    108.000000   50.916667      4075.000000  10.909091
std       4.472136   60.003725      2717.995585   7.354652
min     101.000000   -5.000000      -500.000000   0.000000
25%     104.500000   26.500000      2325.000000   5.000000
50%     108.000000   29.500000      3950.000000  10.000000
75%     111.500000   36.750000      5750.000000  15.000000
max     115.000000  200.000000      9000.000000  25.000000

In [8]:

# Q7. Number of unique values in every column
df.nunique()

Customer_ID        15
Name               13
Age                12
Gender              7
City               11
Purchase_Amount    11
Discount            6
Department          7
Joining_Date       12
Email              10
dtype: int64

In [9]:


# Q7. Number of unique values in every column
df.nunique()

Customer_ID        15
Name               13
Age                12
Gender              7
City               11
Purchase_Amount    11
Discount            6
Department          7
Joining_Date       12
Email              10
dtype: int64

In [10]:

# Q8. Find the total number of missing values in each column
df.isnull().sum()

Customer_ID        0
Name               2
Age                3
Gender             2
City               2
Purchase_Amount    3
Discount           4
Department         2
Joining_Date       2
Email              2
dtype: int64

In [11]:

# Q9. Find the percentage of missing values in each column
(df.isnull().sum() / len(df)) * 100

Customer_ID         0.000000
Name               13.333333
Age                20.000000
Gender             13.333333
City               13.333333
Purchase_Amount    20.000000
Discount           26.666667
Department         13.333333
Joining_Date       13.333333
Email              13.333333
dtype: float64

In [12]:

# Q10. Display only the rows that contain missing values
df[df.isnull().any(axis=1)]

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email
2,103,ARUN,NaN,M,CHENNAI,3200.0,NaN,Clothing,2020-08-10,arun@gmail.com
3,104,Meena,28.0,female,Chennai,NaN,15.0,CLOTHING,2023-02-30,meena@gmail
4,105,NaN,150.0,NaN,NaN,7500.0,20.0,NaN,NaN,NaN
5,106,Suresh,35.0,MALE,Mumbai,1200.0,NaN,Grocery,2021-06-15,suresh@gmail.com
8,109,Priya,NaN,Female,Bangalore,5600.0,0.0,Clothing,2021-06-15,priya@gmail.com
9,110,NaN,42.0,F,bangalore,NaN,25.0,GROCERY,2020-03-20,kiran@gmail.com
10,111,Kiran,19.0,male,NaN,1800.0,NaN,NaN,2024-01-10,NaN
11,112,Meera,200.0,NaN,Delhi,9000.0,15.0,Electronics,2022-12-32,meera@gmail.com
13,114,sneha,NaN,Female,Kochi,6200.0,NaN,Grocery,NaN,sneha@gmail
14,115,Suresh,27.0,female,KOCHI,NaN,5.0,CLOTHING,2021-09-25,suresh@gmail.com

In [13]:

# Q11. Remove rows where Name is missing
df_no_missing_names = df.dropna(subset=["Name"])
df_no_missing_names

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email
0,101,Rahul,25.0,Male,Kochi,2500.0,10.0,Electronics,2022-01-15,rahul@gmail.com
1,102,Priya,30.0,Female,kochi,4500.0,5.0,electronics,2021-05-20,priya@gmail.com
2,103,ARUN,NaN,M,CHENNAI,3200.0,NaN,Clothing,2020-08-10,arun@gmail.com
3,104,Meena,28.0,female,Chennai,NaN,15.0,CLOTHING,2023-02-30,meena@gmail
5,106,Suresh,35.0,MALE,Mumbai,1200.0,NaN,Grocery,2021-06-15,suresh@gmail.com
6,107,Anu,-5.0,F,mumbai,-500.0,5.0,grocery,2022-13-10,anu@gmail
7,108,rahul,29.0,Male,Kochi,3400.0,10.0,Electronics,2020-11-25,rahul@gmail.com
8,109,Priya,NaN,Female,Bangalore,5600.0,0.0,Clothing,2021-06-15,priya@gmail.com
10,111,Kiran,19.0,male,NaN,1800.0,NaN,NaN,2024-01-10,NaN
11,112,Meera,200.0,NaN,Delhi,9000.0,15.0,Electronics,2022-12-32,meera@gmail.com
12,113,John,31.0,Male,delhi,4500.0,10.0,electronics,2023-05-18,john@gmail.com
13,114,sneha,NaN,Female,Kochi,6200.0,NaN,Grocery,NaN,sneha@gmail
14,115,Suresh,27.0,female,KOCHI,NaN,5.0,CLOTHING,2021-09-25,suresh@gmail.com

In [14]:

# Q12. Fill missing values in Gender
df["Gender"] = df["Gender"].fillna("Unknown")
df["Gender"]

0        Male
1      Female
2           M
3      female
4     Unknown
5        MALE
6           F
7        Male
8      Female
9           F
10       male
11    Unknown
12       Male
13     Female
14     female
Name: Gender, dtype: str

In [15]:

# Q13. Fill missing values in City
df["City"] = df["City"].fillna("Unknown")
df["City"]

0         Kochi
1         kochi
2       CHENNAI
3       Chennai
4       Unknown
5        Mumbai
6        mumbai
7         Kochi
8     Bangalore
9     bangalore
10      Unknown
11        Delhi
12        delhi
13        Kochi
14        KOCHI
Name: City, dtype: str

In [16]:

# Q14. Fill missing values in Department
df["Department"] = df["Department"].fillna("Unknown")
df["Department"]

0     Electronics
1     electronics
2        Clothing
3        CLOTHING
4         Unknown
5         Grocery
6         grocery
7     Electronics
8        Clothing
9         GROCERY
10        Unknown
11    Electronics
12    electronics
13        Grocery
14       CLOTHING
Name: Department, dtype: str

In [17]:

# Q15. Fill missing Purchase_Amount values with the median
df["Purchase_Amount"] = df["Purchase_Amount"].fillna(
    df["Purchase_Amount"].median()
)
df["Purchase_Amount"]

0     2500.0
1     4500.0
2     3200.0
3     3950.0
4     7500.0
5     1200.0
6     -500.0
7     3400.0
8     5600.0
9     3950.0
10    1800.0
11    9000.0
12    4500.0
13    6200.0
14    3950.0
Name: Purchase_Amount, dtype: float64

In [18]:

# Q16. Fill missing Discount values with the median
df["Discount"] = df["Discount"].fillna(df["Discount"].median())
df["Discount"]

0     10.0
1      5.0
2     10.0
3     15.0
4     20.0
5     10.0
6      5.0
7     10.0
8      0.0
9     25.0
10    10.0
11    15.0
12    10.0
13    10.0
14     5.0
Name: Discount, dtype: float64

In [19]:

# Q17. Keep rows with at least 8 non-missing values
df_thresh = df.dropna(thresh=8)
df_thresh

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email
0,101,Rahul,25.0,Male,Kochi,2500.0,10.0,Electronics,2022-01-15,rahul@gmail.com
1,102,Priya,30.0,Female,kochi,4500.0,5.0,electronics,2021-05-20,priya@gmail.com
2,103,ARUN,NaN,M,CHENNAI,3200.0,10.0,Clothing,2020-08-10,arun@gmail.com
3,104,Meena,28.0,female,Chennai,3950.0,15.0,CLOTHING,2023-02-30,meena@gmail
5,106,Suresh,35.0,MALE,Mumbai,1200.0,10.0,Grocery,2021-06-15,suresh@gmail.com
6,107,Anu,-5.0,F,mumbai,-500.0,5.0,grocery,2022-13-10,anu@gmail
7,108,rahul,29.0,Male,Kochi,3400.0,10.0,Electronics,2020-11-25,rahul@gmail.com
8,109,Priya,NaN,Female,Bangalore,5600.0,0.0,Clothing,2021-06-15,priya@gmail.com
9,110,NaN,42.0,F,bangalore,3950.0,25.0,GROCERY,2020-03-20,kiran@gmail.com
10,111,Kiran,19.0,male,Unknown,1800.0,10.0,Unknown,2024-01-10,NaN
11,112,Meera,200.0,Unknown,Delhi,9000.0,15.0,Electronics,2022-12-32,meera@gmail.com
12,113,John,31.0,Male,delhi,4500.0,10.0,electronics,2023-05-18,john@gmail.com
13,114,sneha,NaN,Female,Kochi,6200.0,10.0,Grocery,NaN,sneha@gmail
14,115,Suresh,27.0,female,KOCHI,3950.0,5.0,CLOTHING,2021-09-25,suresh@gmail.com

In [20]:

# Q18. Check whether duplicate rows exist
df.duplicated().any()

np.False_

In [21]:

# Q19. Find the number of duplicate rows
df.duplicated().sum()

np.int64(0)

In [22]:

# Q20. Display the duplicate records
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Purchase_Amount, Discount, Department, Joining_Date, Email]
Index: []

In [23]:

# Q21. Remove duplicate records
df = df.drop_duplicates()
df

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email
0,101,Rahul,25.0,Male,Kochi,2500.0,10.0,Electronics,2022-01-15,rahul@gmail.com
1,102,Priya,30.0,Female,kochi,4500.0,5.0,electronics,2021-05-20,priya@gmail.com
2,103,ARUN,NaN,M,CHENNAI,3200.0,10.0,Clothing,2020-08-10,arun@gmail.com
3,104,Meena,28.0,female,Chennai,3950.0,15.0,CLOTHING,2023-02-30,meena@gmail
4,105,NaN,150.0,Unknown,Unknown,7500.0,20.0,Unknown,NaN,NaN
5,106,Suresh,35.0,MALE,Mumbai,1200.0,10.0,Grocery,2021-06-15,suresh@gmail.com
6,107,Anu,-5.0,F,mumbai,-500.0,5.0,grocery,2022-13-10,anu@gmail
7,108,rahul,29.0,Male,Kochi,3400.0,10.0,Electronics,2020-11-25,rahul@gmail.com
8,109,Priya,NaN,Female,Bangalore,5600.0,0.0,Clothing,2021-06-15,priya@gmail.com
9,110,NaN,42.0,F,bangalore,3950.0,25.0,GROCERY,2020-03-20,kiran@gmail.com
10,111,Kiran,19.0,male,Unknown,1800.0,10.0,Unknown,2024-01-10,NaN
11,112,Meera,200.0,Unknown,Delhi,9000.0,15.0,Electronics,2022-12-32,meera@gmail.com
12,113,John,31.0,Male,delhi,4500.0,10.0,electronics,2023-05-18,john@gmail.com
13,114,sneha,NaN,Female,Kochi,6200.0,10.0,Grocery,NaN,sneha@gmail
14,115,Suresh,27.0,female,KOCHI,3950.0,5.0,CLOTHING,2021-09-25,suresh@gmail.com

In [24]:

# Q22. Check whether duplicate Customer_ID values exist
df["Customer_ID"].duplicated().any()

np.False_

In [25]:

# Q23. Remove unnecessary spaces from the Name column
df["Name"] = df["Name"].str.strip()
df["Name"]

0      Rahul
1      Priya
2       ARUN
3      Meena
4        NaN
5     Suresh
6        Anu
7      rahul
8      Priya
9        NaN
10     Kiran
11     Meera
12      John
13     sneha
14    Suresh
Name: Name, dtype: str

In [26]:

# Q24. Standardize names using consistent capitalization
df["Name"] = df["Name"].str.title()
df["Name"]

0      Rahul
1      Priya
2       Arun
3      Meena
4        NaN
5     Suresh
6        Anu
7      Rahul
8      Priya
9        NaN
10     Kiran
11     Meera
12      John
13     Sneha
14    Suresh
Name: Name, dtype: str

In [27]:

# Q25. Standardize city names
df["City"] = df["City"].str.title()
df["City"]

0         Kochi
1         Kochi
2       Chennai
3       Chennai
4       Unknown
5        Mumbai
6        Mumbai
7         Kochi
8     Bangalore
9     Bangalore
10      Unknown
11        Delhi
12        Delhi
13        Kochi
14        Kochi
Name: City, dtype: str

In [28]:

# Q26. Standardize department names
df["Department"] = df["Department"].str.title()
df["Department"]

0     Electronics
1     Electronics
2        Clothing
3        Clothing
4         Unknown
5         Grocery
6         Grocery
7     Electronics
8        Clothing
9         Grocery
10        Unknown
11    Electronics
12    Electronics
13        Grocery
14       Clothing
Name: Department, dtype: str

In [29]:

# Q27. Standardize gender values, mapping M/male variants to Male and F/female variants to Female
df["Gender"] = (
    df["Gender"].str.strip().str.lower().map({
        "m": "Male",
        "male": "Male",
        "f": "Female",
        "female": "Female"
    })
)
df["Gender"]

0       Male
1     Female
2       Male
3     Female
4        NaN
5       Male
6     Female
7       Male
8     Female
9     Female
10      Male
11       NaN
12      Male
13    Female
14    Female
Name: Gender, dtype: str

In [30]:

# Q28. Find customers whose age is greater than 100.
df[df["Age"] > 100]

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email
4,105,NaN,150.0,NaN,Unknown,7500.0,20.0,Unknown,NaN,NaN
11,112,Meera,200.0,NaN,Delhi,9000.0,15.0,Electronics,2022-12-32,meera@gmail.com

In [31]:

# Q29. Find customers whose age is less than 0.
df[df["Age"] < 0]

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email
6,107,Anu,-5.0,Female,Mumbai,-500.0,5.0,Grocery,2022-13-10,anu@gmail

In [32]:

# Q30. Identify all invalid age values.
invalid_ages = df[(df["Age"] > 100) | (df["Age"] < 0)]
invalid_ages

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email
4,105,NaN,150.0,NaN,Unknown,7500.0,20.0,Unknown,NaN,NaN
6,107,Anu,-5.0,Female,Mumbai,-500.0,5.0,Grocery,2022-13-10,anu@gmail
11,112,Meera,200.0,NaN,Delhi,9000.0,15.0,Electronics,2022-12-32,meera@gmail.com

In [33]:

# Q31. Replace invalid age values with missing values.
df.loc[(df["Age"] > 100) | (df["Age"] < 0), "Age"] = np.nan
df["Age"]

0     25.0
1     30.0
2      NaN
3     28.0
4      NaN
5     35.0
6      NaN
7     29.0
8      NaN
9     42.0
10    19.0
11     NaN
12    31.0
13     NaN
14    27.0
Name: Age, dtype: float64

In [34]:

# Q32. Find customers whose Purchase_Amount is negative.
df[df["Purchase_Amount"] < 0]

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email
6,107,Anu,NaN,Female,Mumbai,-500.0,5.0,Grocery,2022-13-10,anu@gmail

In [35]:

# Q33. Replace invalid purchase amounts with missing values.
df.loc[df["Purchase_Amount"] < 0, "Purchase_Amount"] = np.nan
df["Purchase_Amount"]

0     2500.0
1     4500.0
2     3200.0
3     3950.0
4     7500.0
5     1200.0
6        NaN
7     3400.0
8     5600.0
9     3950.0
10    1800.0
11    9000.0
12    4500.0
13    6200.0
14    3950.0
Name: Purchase_Amount, dtype: float64

In [36]:

# Q34. Find customers whose discount is greater than 100.
df[df["Discount"] > 100]

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Purchase_Amount, Discount, Department, Joining_Date, Email]
Index: []

In [37]:

# Q35. Convert Joining_Date into a proper datetime column.
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"], errors="coerce")
df["Joining_Date"]

0    2022-01-15
1    2021-05-20
2    2020-08-10
3           NaT
4           NaT
5    2021-06-15
6           NaT
7    2020-11-25
8    2021-06-15
9    2020-03-20
10   2024-01-10
11          NaT
12   2023-05-18
13          NaT
14   2021-09-25
Name: Joining_Date, dtype: datetime64[us]

In [38]:

# Q36. Identify invalid dates.
invalid_dates = df[df["Joining_Date"].isna()]
invalid_dates[["Customer_ID", "Joining_Date"]]

    Customer_ID Joining_Date
3           104          NaT
4           105          NaT
6           107          NaT
11          112          NaT
13          114          NaT

In [39]:

# Q37. Find customers whose joining date could not be converted into a valid date.
df[df["Joining_Date"].isna()][["Customer_ID", "Name", "Joining_Date"]]

    Customer_ID   Name Joining_Date
3           104  Meena          NaT
4           105    NaN          NaT
6           107    Anu          NaT
11          112  Meera          NaT
13          114  Sneha          NaT

In [40]:

# Q38. Create Joining_Year.
df["Joining_Year"] = df["Joining_Date"].dt.year
df[["Customer_ID", "Joining_Date", "Joining_Year"]]

    Customer_ID Joining_Date  Joining_Year
0           101   2022-01-15        2022.0
1           102   2021-05-20        2021.0
2           103   2020-08-10        2020.0
3           104          NaT           NaN
4           105          NaT           NaN
5           106   2021-06-15        2021.0
6           107          NaT           NaN
7           108   2020-11-25        2020.0
8           109   2021-06-15        2021.0
9           110   2020-03-20        2020.0
10          111   2024-01-10        2024.0
11          112          NaT           NaN
12          113   2023-05-18        2023.0
13          114          NaT           NaN
14          115   2021-09-25        2021.0

In [41]:

# Q39. Create Joining_Month.
df["Joining_Month"] = df["Joining_Date"].dt.month
df[["Customer_ID", "Joining_Date", "Joining_Month"]]

    Customer_ID Joining_Date  Joining_Month
0           101   2022-01-15            1.0
1           102   2021-05-20            5.0
2           103   2020-08-10            8.0
3           104          NaT            NaN
4           105          NaT            NaN
5           106   2021-06-15            6.0
6           107          NaT            NaN
7           108   2020-11-25           11.0
8           109   2021-06-15            6.0
9           110   2020-03-20            3.0
10          111   2024-01-10            1.0
11          112          NaT            NaN
12          113   2023-05-18            5.0
13          114          NaT            NaN
14          115   2021-09-25            9.0

In [42]:

# Q40. Find customers who joined after January 1, 2022.
df[df["Joining_Date"] > pd.Timestamp("2022-01-01")][["Customer_ID", "Name", "Joining_Date"]]

    Customer_ID   Name Joining_Date
0           101  Rahul   2022-01-15
10          111  Kiran   2024-01-10
12          113   John   2023-05-18

In [43]:

# Q41. Find customers whose email is missing.
df[df["Email"].isna()][["Customer_ID", "Name", "Email"]]

    Customer_ID   Name Email
4           105    NaN   NaN
10          111  Kiran   NaN

In [44]:

# Q42. Find emails that do not contain @.
missing_at = df[~df["Email"].fillna("").astype(str).str.contains("@", na=False)]
missing_at[["Customer_ID", "Name", "Email"]]

    Customer_ID   Name Email
4           105    NaN   NaN
10          111  Kiran   NaN

In [45]:

# Q43. Find emails that do not contain a valid-looking domain such as .com.
invalid_domains = df[~df["Email"].fillna("").astype(str).str.contains(r"@.+\.[A-Za-z]{2,}", na=False)]
invalid_domains[["Customer_ID", "Name", "Email"]]

    Customer_ID   Name        Email
3           104  Meena  meena@gmail
4           105    NaN          NaN
6           107    Anu    anu@gmail
10          111  Kiran          NaN
13          114  Sneha  sneha@gmail

In [46]:

# Q44. Create Email_Status with the values Valid, Invalid, and Missing.
email_missing = df["Email"].isna() | df["Email"].fillna("").astype(str).str.strip().eq("")
email_valid = df["Email"].fillna("").astype(str).str.contains(r"@.+\.[A-Za-z]{2,}", na=False)
df["Email_Status"] = np.select([email_missing, email_valid], ["Missing", "Valid"], default="Invalid")
df[["Customer_ID", "Email", "Email_Status"]]

    Customer_ID             Email Email_Status
0           101   rahul@gmail.com        Valid
1           102   priya@gmail.com        Valid
2           103    arun@gmail.com        Valid
3           104       meena@gmail      Invalid
4           105               NaN      Missing
5           106  suresh@gmail.com        Valid
6           107         anu@gmail      Invalid
7           108   rahul@gmail.com        Valid
8           109   priya@gmail.com        Valid
9           110   kiran@gmail.com        Valid
10          111               NaN      Missing
11          112   meera@gmail.com        Valid
12          113    john@gmail.com        Valid
13          114       sneha@gmail      Invalid
14          115  suresh@gmail.com        Valid

In [47]:

# Q45. Find all customers from Kochi.
df[df["City"] == "Kochi"]

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email,Joining_Year,Joining_Month,Email_Status
0,101,Rahul,25.0,Male,Kochi,2500.0,10.0,Electronics,2022-01-15,rahul@gmail.com,2022.0,1.0,Valid
1,102,Priya,30.0,Female,Kochi,4500.0,5.0,Electronics,2021-05-20,priya@gmail.com,2021.0,5.0,Valid
7,108,Rahul,29.0,Male,Kochi,3400.0,10.0,Electronics,2020-11-25,rahul@gmail.com,2020.0,11.0,Valid
13,114,Sneha,NaN,Female,Kochi,6200.0,10.0,Grocery,NaT,sneha@gmail,NaN,NaN,Invalid
14,115,Suresh,27.0,Female,Kochi,3950.0,5.0,Clothing,2021-09-25,suresh@gmail.com,2021.0,9.0,Valid

In [48]:

# Q46. Find all customers from Mumbai.
df[df["City"] == "Mumbai"]

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email,Joining_Year,Joining_Month,Email_Status
5,106,Suresh,35.0,Male,Mumbai,1200.0,10.0,Grocery,2021-06-15,suresh@gmail.com,2021.0,6.0,Valid
6,107,Anu,NaN,Female,Mumbai,NaN,5.0,Grocery,NaT,anu@gmail,NaN,NaN,Invalid

In [49]:

# Q47. Find customers whose purchase amount is greater than ₹5,000.
df[df["Purchase_Amount"] > 5000]

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email,Joining_Year,Joining_Month,Email_Status
4,105,NaN,NaN,NaN,Unknown,7500.0,20.0,Unknown,NaT,NaN,NaN,NaN,Missing
8,109,Priya,NaN,Female,Bangalore,5600.0,0.0,Clothing,2021-06-15,priya@gmail.com,2021.0,6.0,Valid
11,112,Meera,NaN,NaN,Delhi,9000.0,15.0,Electronics,NaT,meera@gmail.com,NaN,NaN,Valid
13,114,Sneha,NaN,Female,Kochi,6200.0,10.0,Grocery,NaT,sneha@gmail,NaN,NaN,Invalid

In [50]:

# Q48. Find customers whose age is between 25 and 40.
df[(df["Age"] >= 25) & (df["Age"] <= 40)]

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email,Joining_Year,Joining_Month,Email_Status
0,101,Rahul,25.0,Male,Kochi,2500.0,10.0,Electronics,2022-01-15,rahul@gmail.com,2022.0,1.0,Valid
1,102,Priya,30.0,Female,Kochi,4500.0,5.0,Electronics,2021-05-20,priya@gmail.com,2021.0,5.0,Valid
3,104,Meena,28.0,Female,Chennai,3950.0,15.0,Clothing,NaT,meena@gmail,NaN,NaN,Invalid
5,106,Suresh,35.0,Male,Mumbai,1200.0,10.0,Grocery,2021-06-15,suresh@gmail.com,2021.0,6.0,Valid
7,108,Rahul,29.0,Male,Kochi,3400.0,10.0,Electronics,2020-11-25,rahul@gmail.com,2020.0,11.0,Valid
12,113,John,31.0,Male,Delhi,4500.0,10.0,Electronics,2023-05-18,john@gmail.com,2023.0,5.0,Valid
14,115,Suresh,27.0,Female,Kochi,3950.0,5.0,Clothing,2021-09-25,suresh@gmail.com,2021.0,9.0,Valid

In [51]:

# Q49. Find customers from the Electronics department who spent more than ₹3,000.
df[(df["Department"] == "Electronics") & (df["Purchase_Amount"] > 3000)]

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email,Joining_Year,Joining_Month,Email_Status
1,102,Priya,30.0,Female,Kochi,4500.0,5.0,Electronics,2021-05-20,priya@gmail.com,2021.0,5.0,Valid
7,108,Rahul,29.0,Male,Kochi,3400.0,10.0,Electronics,2020-11-25,rahul@gmail.com,2020.0,11.0,Valid
11,112,Meera,NaN,NaN,Delhi,9000.0,15.0,Electronics,NaT,meera@gmail.com,NaN,NaN,Valid
12,113,John,31.0,Male,Delhi,4500.0,10.0,Electronics,2023-05-18,john@gmail.com,2023.0,5.0,Valid

In [52]:

# Q50. Find customers who are either from Kochi or Delhi.
df[df["City"].isin(["Kochi", "Delhi"])]

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email,Joining_Year,Joining_Month,Email_Status
0,101,Rahul,25.0,Male,Kochi,2500.0,10.0,Electronics,2022-01-15,rahul@gmail.com,2022.0,1.0,Valid
1,102,Priya,30.0,Female,Kochi,4500.0,5.0,Electronics,2021-05-20,priya@gmail.com,2021.0,5.0,Valid
7,108,Rahul,29.0,Male,Kochi,3400.0,10.0,Electronics,2020-11-25,rahul@gmail.com,2020.0,11.0,Valid
11,112,Meera,NaN,NaN,Delhi,9000.0,15.0,Electronics,NaT,meera@gmail.com,NaN,NaN,Valid
12,113,John,31.0,Male,Delhi,4500.0,10.0,Electronics,2023-05-18,john@gmail.com,2023.0,5.0,Valid
13,114,Sneha,NaN,Female,Kochi,6200.0,10.0,Grocery,NaT,sneha@gmail,NaN,NaN,Invalid
14,115,Suresh,27.0,Female,Kochi,3950.0,5.0,Clothing,2021-09-25,suresh@gmail.com,2021.0,9.0,Valid

In [53]:

# Q51. Calculate the average purchase amount.
df["Purchase_Amount"].mean()

np.float64(4375.0)

In [54]:

# Q52. Calculate the median purchase amount.
df["Purchase_Amount"].median()

np.float64(3950.0)

In [55]:

# Q53. Find the minimum and maximum purchase amount.
df["Purchase_Amount"].agg(["min", "max"])

min    1200.0
max    9000.0
Name: Purchase_Amount, dtype: float64

In [56]:

# Q54. Calculate the average age.
df["Age"].mean()

np.float64(29.555555555555557)

In [57]:

# Q55. Find the average purchase amount for each city.
df.groupby("City")["Purchase_Amount"].mean()

City
Bangalore    4775.0
Chennai      3575.0
Delhi        6750.0
Kochi        4110.0
Mumbai       1200.0
Unknown      4650.0
Name: Purchase_Amount, dtype: float64

In [58]:

# Q56. Find the average purchase amount for each department.
df.groupby("Department")["Purchase_Amount"].mean()

Department
Clothing       4175.000000
Electronics    4780.000000
Grocery        3783.333333
Unknown        4650.000000
Name: Purchase_Amount, dtype: float64

In [59]:

# Q57. Find the maximum purchase amount for each department.
df.groupby("Department")["Purchase_Amount"].max()

Department
Clothing       5600.0
Electronics    9000.0
Grocery        6200.0
Unknown        7500.0
Name: Purchase_Amount, dtype: float64

In [60]:

# Q58. Count the number of customers in each city.
df["City"].value_counts()

City
Kochi        5
Chennai      2
Unknown      2
Mumbai       2
Bangalore    2
Delhi        2
Name: count, dtype: int64

In [61]:

# Q59. Count the number of customers in each department.
df["Department"].value_counts()

Department
Electronics    5
Clothing       4
Grocery        4
Unknown        2
Name: count, dtype: int64

In [62]:

# Q60. Calculate the average discount for each department.
df.groupby("Department")["Discount"].mean()

Department
Clothing        7.5
Electronics    10.0
Grocery        12.5
Unknown        15.0
Name: Discount, dtype: float64

In [63]:

# Final Challenge: Create a separate cleaned DataFrame from the original data dictionary.
cleaned_df = pd.DataFrame(data).copy()

# Standardize text fields without modifying the original data dictionary.
cleaned_df["Name"] = cleaned_df["Name"].astype("string").str.strip().str.title()
cleaned_df["City"] = cleaned_df["City"].astype("string").str.strip().str.title()
cleaned_df["Department"] = cleaned_df["Department"].astype("string").str.strip().str.title()

cleaned_df["Gender"] = (
    cleaned_df["Gender"].astype("string").str.strip().str.lower().map({
        "m": "Male",
        "male": "Male",
        "f": "Female",
        "female": "Female"
    })
)

# Remove duplicate records.
cleaned_df = cleaned_df.drop_duplicates()

# Convert numeric columns and handle invalid values.
cleaned_df["Age"] = pd.to_numeric(cleaned_df["Age"], errors="coerce")
cleaned_df.loc[(cleaned_df["Age"] < 0) | (cleaned_df["Age"] > 100), "Age"] = np.nan

cleaned_df["Purchase_Amount"] = pd.to_numeric(cleaned_df["Purchase_Amount"], errors="coerce")
cleaned_df.loc[cleaned_df["Purchase_Amount"] < 0, "Purchase_Amount"] = np.nan

cleaned_df["Discount"] = pd.to_numeric(cleaned_df["Discount"], errors="coerce")

# Convert dates safely and derive year/month columns.
cleaned_df["Joining_Date"] = pd.to_datetime(cleaned_df["Joining_Date"], errors="coerce")
cleaned_df["Joining_Year"] = cleaned_df["Joining_Date"].dt.year
cleaned_df["Joining_Month"] = cleaned_df["Joining_Date"].dt.month

# Email validation and status.
cleaned_df["Email"] = cleaned_df["Email"].astype("string")
email_missing = cleaned_df["Email"].isna() | cleaned_df["Email"].str.strip().eq("")
email_valid = cleaned_df["Email"].fillna("").astype(str).str.contains(r"@.+\.[A-Za-z]{2,}", na=False)
cleaned_df["Email_Status"] = np.select([email_missing, email_valid], ["Missing", "Valid"], default="Invalid")

# Final summary metrics.
print("Number of records:", len(cleaned_df))
print("Number of columns:", cleaned_df.shape[1])
print("Missing values:\n", cleaned_df.isna().sum())
print("Duplicate records:", cleaned_df.duplicated().sum())
print("Average age:", cleaned_df["Age"].mean())
print("Average purchase amount:", cleaned_df["Purchase_Amount"].mean())
print("Maximum purchase amount:", cleaned_df["Purchase_Amount"].max())
print("Minimum purchase amount:", cleaned_df["Purchase_Amount"].min())
print("Number of cities:", cleaned_df["City"].nunique())
print("Number of departments:", cleaned_df["Department"].nunique())
print("Number of valid emails:", (cleaned_df["Email_Status"] == "Valid").sum())
print("Number of invalid emails:", (cleaned_df["Email_Status"] == "Invalid").sum())

cleaned_df

Number of records: 15
Number of columns: 13
Missing values:
 Customer_ID        0
Name               2
Age                6
Gender             2
City               2
Purchase_Amount    4
Discount           4
Department         2
Joining_Date       5
Email              2
Joining_Year       5
Joining_Month      5
Email_Status       0
dtype: int64
Duplicate records: 0
Average age: 29.555555555555557
Average purchase amount: 4490.909090909091
Maximum purchase amount: 9000.0
Minimum purchase amount: 1200.0
Number of cities: 5
Number of departments: 3
Number of valid emails: 10
Number of invalid emails: 3

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Discount,Department,Joining_Date,Email,Joining_Year,Joining_Month,Email_Status
0,101,Rahul,25.0,Male,Kochi,2500.0,10.0,Electronics,2022-01-15,rahul@gmail.com,2022.0,1.0,Valid
1,102,Priya,30.0,Female,Kochi,4500.0,5.0,Electronics,2021-05-20,priya@gmail.com,2021.0,5.0,Valid
2,103,Arun,NaN,Male,Chennai,3200.0,NaN,Clothing,2020-08-10,arun@gmail.com,2020.0,8.0,Valid
3,104,Meena,28.0,Female,Chennai,NaN,15.0,Clothing,NaT,meena@gmail,NaN,NaN,Invalid
4,105,<NA>,NaN,NaN,<NA>,7500.0,20.0,<NA>,NaT,<NA>,NaN,NaN,Missing
5,106,Suresh,35.0,Male,Mumbai,1200.0,NaN,Grocery,2021-06-15,suresh@gmail.com,2021.0,6.0,Valid
6,107,Anu,NaN,Female,Mumbai,NaN,5.0,Grocery,NaT,anu@gmail,NaN,NaN,Invalid
7,108,Rahul,29.0,Male,Kochi,3400.0,10.0,Electronics,2020-11-25,rahul@gmail.com,2020.0,11.0,Valid
8,109,Priya,NaN,Female,Bangalore,5600.0,0.0,Clothing,2021-06-15,priya@gmail.com,2021.0,6.0,Valid
9,110,<NA>,42.0,Female,Bangalore,NaN,25.0,Grocery,2020-03-20,kiran@gmail.com,2020.0,3.0,Valid
10,111,Kiran,19.0,Male,<NA>,1800.0,NaN,<NA>,2024-01-10,<NA>,2024.0,1.0,Missing
11,112,Meera,NaN,NaN,Delhi,9000.0,15.0,Electronics,NaT,meera@gmail.com,NaN,NaN,Valid
12,113,John,31.0,Male,Delhi,4500.0,10.0,Electronics,2023-05-18,john@gmail.com,2023.0,5.0,Valid
13,114,Sneha,NaN,Female,Kochi,6200.0,NaN,Grocery,NaT,sneha@gmail,NaN,NaN,Invalid
14,115,Suresh,27.0,Female,Kochi,NaN,5.0,Clothing,2021-09-25,suresh@gmail.com,2021.0,9.0,Valid